# примеры API-запросов

@baseUrl = http://localhost:8000/api

###

# создание датчика
POST {{baseUrl}}/sensors/
Content-Type: application/json

{
  "name": "ESP32",
  "description": "Датчик на кухне за холодильником"
}

###

# обновление датчика
PATCH {{baseUrl}}/sensors/25/
Content-Type: application/json

{
  "description": "Перенес датчик на балкон 123412"
}

###

# добавление измерения
POST {{baseUrl}}/measurements/
Content-Type: application/json

{
  "sensor": 4,
  "temperature": 27
}

###

# добавление измерения с фото
POST {{baseUrl}}/measurements/
Content-Type: application/json

{
  "sensor": 4,
  "temperature": 27,
  "image": ""
}

###

# получение датчиков
GET {{baseUrl}}/sensors/
Content-Type: application/json

###

# получение информации по датчику
GET {{baseUrl}}/sensors/3/
Content-Type: application/json
